# The URL the site will be built for
base_url = "https://www.zymologia.fi/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Alzymologist Oy"
description = "Laboratory for microbrewers"
generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/info/contacts#starthere", name = "Contacts"},
    {url = "/info/services#starthere", name = "Services"},
    {url = "/info/methods#starthere", name = "Lab analysis"},
    {url = "/info/pricing#starthere", name = "Pricing"},
    {url = "/info/about#starthere", name = "About"},
    {url = "/info/gdpr#starthere", name = "Privacy policy"},
    {url = "/atom.xml", name = "Atom feed"},
]
